version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-deps:
        update-types:
          - "minor"
          - "patch"