package store

// Template constants for code generation

// InterfaceTemplate is the template for generating store interfaces.
const InterfaceTemplate = `// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
package {{ .Store.Package }}

import (
{{- range .Imports }}
    {{- if .Alias }}{{ .Alias }} "{{ .Path }}"{{ else }}"{{ .Path }}"{{ end }}
{{- end }}
)

// {{ .Store.Interface }} defines the interface for store operations
type {{ .Store.Interface }} interface {
{{- range .Store.Queries }}
    {{ .Name }}(ctx *gofr.Context{{- range .Params }}, {{ .Name }} {{ .Type }}{{- end }}) (
        {{- if eq .Returns "single" }}{{ .Model | getModelType }}
        {{- else if eq .Returns "multiple" }}[]{{ .Model | getModelType }}
        {{- else if eq .Returns "count" }}int64
        {{- else }}any
        {{- end }}, error)
{{- end }}
}
`

// ImplementationTemplate is the template for generating store implementations.
const ImplementationTemplate = `// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
package {{ .Store.Package }}

import (
{{- range .Imports }}
    {{- if .Alias }}{{ .Alias }} "{{ .Path }}"{{ else }}"{{ .Path }}"{{ end }}
{{- end }}
)

// {{ .Store.Implementation }} implements {{ .Store.Interface }}
type {{ .Store.Implementation }} struct {
    // Add any dependencies here (e.g., database connection)
}

// New{{ .Store.Interface }} creates a new instance of {{ .Store.Interface }}
func New{{ .Store.Interface }}() {{ .Store.Interface }} {
    return &{{ .Store.Implementation }}{}
}
{{- range .Store.Queries }}

// {{ .Name }} {{ if .Description }}{{ .Description }}{{ else }}executes the {{ .Name }} query{{ end }}
func (s *{{ $.Store.Implementation }}) {{ .Name }}(ctx *gofr.Context{{- range .Params }}, {{ .Name }} {{ .Type }}` +
	`{{- end }}) (
    {{- if eq .Returns "single" }}{{ .Model | getModelType }}
    {{- else if eq .Returns "multiple" }}[]{{ .Model | getModelType }}
    {{- else if eq .Returns "count" }}int64
    {{- else }}any
    {{- end }}, error) {

    // TODO: Implement {{ .Name }} query
    // SQL: {{ .SQL }}
    {{- if eq .Type "select" }}
        {{- if eq .Returns "single" }}
    var result {{ .Model | getModelType }}
    // Implement single row selection using ctx.SQL()
    // Example: err := ctx.SQL().QueryRowContext(ctx, "{{ .SQL }}", {{ range $i, $param := .Params }}{{if $i}}, ` +
	`{{end}}{{ $param.Name }}{{end}}).Scan(&result.Field1, &result.Field2, ...)
    return result, nil
        {{- else if eq .Returns "multiple" }}
    var results []{{ .Model | getModelType }}
    // Implement multiple row selection using ctx.SQL()
    // Example: rows, err := ctx.SQL().QueryContext(ctx, "{{ .SQL }}", {{ range $i, $param := .Params }}{{if $i}},` +
	` {{end}}{{ $param.Name }}{{end}})
    return results, nil
        {{- else if eq .Returns "count" }}
    var count int64
    // Implement count query using ctx.SQL()
    // Example: err := ctx.SQL().QueryRowContext(ctx, "{{ .SQL }}", {{ range $i, $param := .Params }}{{if $i}}, ` +
	`{{end}}{{ $param.Name }}{{end}}).Scan(&count)
    return count, nil
        {{- else }}
    // Implement custom return type
    return nil, nil
        {{- end }}
    {{- else if eq .Type "insert" }}
    // Implement insert operation using ctx.SQL()
    // Example: result, err := ctx.SQL().ExecContext(ctx, "{{ .SQL }}", {{ range $i, $param := .Params }}{{if $i}}, ` +
	`{{end}}{{ $param.Name }}{{end}})
    return {{ if eq .Returns "single" }}{{ .Model }}{}, {{ else if eq .Returns "count" }}int64(0), {{ else }}nil, ` +
	`{{ end }}nil
    {{- else if eq .Type "update" }}
    // Implement update operation using ctx.SQL()
    // Example: result, err := ctx.SQL().ExecContext(ctx, "{{ .SQL }}", {{ range $i, $param := .Params }}{{if $i}},` +
	` {{end}}{{ $param.Name }}{{end}})
    return {{ if eq .Returns "count" }}int64(0), {{ else }}nil, {{ end }}nil
    {{- else if eq .Type "delete" }}
    // Implement delete operation using ctx.SQL()
    // Example: result, err := ctx.SQL().ExecContext(ctx, "{{ .SQL }}", {{ range $i, $param := .Params }}{{if $i}}, ` +
	`{{end}}{{ $param.Name }}{{end}})
    return {{ if eq .Returns "count" }}int64(0), {{ else }}nil, {{ end }}nil
    {{- end }}
}
{{- end }}
`

// ModelTemplate is the template for generating data models.
const ModelTemplate = `// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
package {{ .Store.Package }}

import (
    "time"
)

// {{ .Model.Name }} represents the {{ .Model.Name }} model
type {{ .Model.Name }} struct {
{{- range .Model.Fields }}
    {{ .Name }} {{ .Type }} ` + "`{{ .Tag }}`" + `
{{- end }}
}

// TableName returns the table name for {{ .Model.Name }}
func ({{ .Model.Name }}) TableName() string {
    return "{{ .Model.Name | lower }}"
}
`

// InitialInterfaceTemplate is the template for initial interface generation.
const InitialInterfaceTemplate = `// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
package {{ .PackageName }}

// import (
//     "gofr.dev/pkg/gofr"
// )

// {{ .InterfaceName }} defines the interface for {{ .StoreName }} store operations
type {{ .InterfaceName }} interface {
    // Add your store methods here
    // Example:
    // GetUserByID(ctx *gofr.Context, id int64) (User, error)
}
`

// InitialStoreTemplate is the template for initial store implementation.
const InitialStoreTemplate = `// Code generated by gofr.dev/cli/gofr.
package {{ .PackageName }}

// import (
//     "gofr.dev/pkg/gofr"
// )

// {{ .ImplementationName }} implements the {{ .InterfaceName }} interface
type {{ .ImplementationName }} struct {
    // Add any dependencies here (e.g., database connection)
}

// New{{ .InterfaceName }} creates a new instance of {{ .InterfaceName }}
func New{{ .InterfaceName }}() {{ .InterfaceName }} {
    return &{{ .ImplementationName }}{}
}

// Add your store method implementations here
// Example:
// func (s *{{ .ImplementationName }}) GetUserByID(ctx *gofr.Context, id int64) (User, error) {
//     // TODO: Implement GetUserByID query
//     var result User
//     err := ctx.SQL().QueryRowContext(ctx, "SELECT id, name FROM users WHERE id = ?", id).` +
	`Scan(&result.ID, &result.Name)
//     return result, err
// }
`

// StoreConfigTemplate is the template for generating store.yaml configuration.
const StoreConfigTemplate = `version: "1.0"

# Shared models across all stores
models:
  # Define your models here
  # Option 1: Generate new model struct
  # - name: "User"
  #   fields:
  #     - name: "ID"
  #       type: "int64"
  #       tag: "db:\"id\" json:\"id\""
  #     - name: "Name"
  #       type: "string"
  #       tag: "db:\"name\" json:\"name\""
  #
  # Option 2: Reference existing model from another package
  # - name: "User"
  #   path: "models/user.go"
  #   package: "test-store-project/models"

# Multiple stores configuration
stores:
  - name: "{{ .StoreName }}"
    package: "{{ .PackageName }}"
    output_dir: "{{ .OutputDir }}"
    interface: "{{ .InterfaceName }}"
    implementation: "{{ .ImplementationName }}"
    queries:
      # Define your queries here
      # Example:
      # - name: "GetUserByID"
      #   sql: "SELECT id, name FROM users WHERE id = ?"
      #   type: "select"
      #   model: "User"
      #   returns: "single"
      #   params:
      #     - name: "id"
      #       type: "int64"
      #   description: "Retrieves a user by their ID"

# Legacy single store format (still supported)
# store:
#   package: "{{ .PackageName }}"
#   output_dir: "{{ .OutputDir }}"
#   interface: "{{ .InterfaceName }}"
#   implementation: "{{ .ImplementationName }}"
# queries:
#   - name: "GetUserByID"
#     sql: "SELECT id, name FROM users WHERE id = ?"
#     type: "select"
#     model: "User"
#     returns: "single"
`

// AllStoresTemplate is the template for generating all.go registry.
const AllStoresTemplate = `// Code generated by gofr.dev/cli/gofr. DO NOT EDIT.
package stores
{{- if .Stores }}

import (
{{- range .Stores }}
    "{{ $.ProjectModule }}/stores/{{ .PackageName }}"
{{- end }}
)
{{- end }}

// All returns all available store implementations
func All() map[string]func() any {
    return map[string]func() any {
{{- range .Stores }}
        "{{ .Name }}": func() any {
            return {{ .PackageName }}.New{{ .InterfaceName }}()
        },
{{- end }}
    }
}

// GetStore returns a specific store by name
func GetStore(name string) any {
    stores := All()
    if storeFunc, exists := stores[name]; exists {
        return storeFunc()
    }
    return nil
}
`
